server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_credentials
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect